kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: paperplanecc/baseline-node20:2025.11.30
    volumes:
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn --registry=https://registry.yarnpkg.com
      - yarn build
    environment:
      CI: false
      S3_ENDPOINT:
        from_secret: S3_ENDPOINT
      S3_REGION:
        from_secret: S3_REGION
      S3_BUCKET_NAME:
        from_secret: S3_BUCKET_NAME
      S3_ACCESS_KEY_ID:
        from_secret: S3_ACCESS_KEY_ID
      S3_SECRET_ACCESS_KEY:
        from_secret: S3_SECRET_ACCESS_KEY

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/cfda-fe/
      - rm -rf /webroot/cfda-fe/*
      - cp -rf ./dist/* /webroot/cfda-fe/

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
